export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_EXPERIENCE = 'GET_EXPERIENCE'
export const GET_FOLLOWERS = 'GET_FOLLOWERS'
export const GET_FOLLOWING = 'GET_FOLLOWING'
export const TOGGLE_FOLLOWING = 'TOGGLE_FOLLOWING'
export const TOGGLE_FOLLOWERS = 'TOGGLE_FOLLOWERS'

